"""Database compatibility layer for local SQLite and hosted PostgreSQL.

When ``DATABASE_URL`` is absent, the application keeps using the Lab 7
SQLite database.  When it is present, the same service code talks to the
Supabase PostgreSQL database through psycopg.
"""

from __future__ import annotations

import os
import re
import sqlite3 as _sqlite3
from collections.abc import Iterator, Sequence
from typing import Any

import psycopg


Error = (_sqlite3.Error, psycopg.Error)
IntegrityError = (_sqlite3.IntegrityError, psycopg.IntegrityError)
Connection = object
Row = _sqlite3.Row


POSTGRES_SCHEMA = (
    """
    CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        email TEXT UNIQUE,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'USER',
        is_locked INTEGER NOT NULL DEFAULT 0,
        failed_attempts INTEGER NOT NULL DEFAULT 0
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS hardware (
        item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        item_name TEXT NOT NULL,
        category TEXT NOT NULL,
        quantity INTEGER NOT NULL CHECK (quantity >= 0),
        unit_price DOUBLE PRECISION NOT NULL CHECK (unit_price >= 0),
        status TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS password_reset_requests (
        request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(id),
        username TEXT NOT NULL,
        email TEXT,
        new_password_hash TEXT,
        status TEXT NOT NULL DEFAULT 'PENDING',
        requested_at TEXT NOT NULL,
        reviewed_at TEXT,
        reviewed_by TEXT,
        resolved_at TEXT,
        resolved_by TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS asset_transactions (
        transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(id),
        borrower_username TEXT NOT NULL,
        item_id BIGINT REFERENCES hardware(item_id) ON DELETE SET NULL,
        item_name_snapshot TEXT NOT NULL,
        quantity INTEGER NOT NULL CHECK (quantity > 0),
        purpose TEXT NOT NULL,
        start_date TEXT NOT NULL,
        expected_return_date TEXT NOT NULL,
        requested_at TEXT NOT NULL,
        approved_at TEXT,
        approved_by TEXT,
        issued_at TEXT,
        issued_by TEXT,
        returned_at TEXT,
        returned_by TEXT,
        rejected_at TEXT,
        rejected_by TEXT,
        cancelled_at TEXT,
        status TEXT NOT NULL DEFAULT 'PENDING'
            CHECK (status IN (
                'PENDING', 'APPROVED', 'REJECTED', 'BORROWED',
                'OVERDUE', 'RETURNED', 'CANCELLED'
            ))
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS web_return_requests (
        return_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        transaction_id BIGINT NOT NULL
            REFERENCES asset_transactions(transaction_id) ON DELETE CASCADE,
        requested_by TEXT NOT NULL,
        requested_at TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'PENDING'
            CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
        resolved_at TEXT,
        resolved_by TEXT,
        UNIQUE (transaction_id, status)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_asset_transactions_item_schedule
    ON asset_transactions(item_id, status, start_date, expected_return_date)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_asset_transactions_user_status
    ON asset_transactions(user_id, status)
    """,
)


def database_url() -> str | None:
    value = os.environ.get("DATABASE_URL", "").strip()
    if value.startswith("postgres://"):
        value = "postgresql://" + value[len("postgres://"):]
    return value or None


def using_postgres() -> bool:
    return database_url() is not None


def _postgres_query(query: str) -> str:
    """Convert SQLite qmark placeholders without touching quoted text."""
    output: list[str] = []
    quote: str | None = None
    index = 0
    while index < len(query):
        char = query[index]
        if quote:
            output.append(char)
            if char == quote:
                if index + 1 < len(query) and query[index + 1] == quote:
                    output.append(query[index + 1])
                    index += 1
                else:
                    quote = None
        elif char in ("'", '"'):
            quote = char
            output.append(char)
        elif char == "?":
            output.append("%s")
        else:
            output.append(char)
        index += 1
    return "".join(output)


class CompatRow(Sequence):
    """Row supporting both numeric and column-name access like sqlite3.Row."""

    def __init__(self, values: Sequence[Any], columns: Sequence[str]):
        self._values = tuple(values)
        self._positions = {name: i for i, name in enumerate(columns)}

    def __getitem__(self, key):
        if isinstance(key, str):
            return self._values[self._positions[key]]
        return self._values[key]

    def __len__(self) -> int:
        return len(self._values)

    def __iter__(self) -> Iterator[Any]:
        return iter(self._values)

    def keys(self):
        return self._positions.keys()


class PostgresCursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self.lastrowid = None
        self._no_result = False

    @property
    def rowcount(self):
        return self._cursor.rowcount

    @property
    def description(self):
        return self._cursor.description

    def execute(self, query: str, params: Sequence[Any] | None = None):
        compact = " ".join(query.strip().split())
        upper = compact.upper()
        self._no_result = False

        if upper.startswith("PRAGMA FOREIGN_KEYS"):
            self._no_result = True
            return self
        if upper == "BEGIN IMMEDIATE":
            query = "BEGIN"

        wants_transaction_id = bool(
            re.match(r"\s*INSERT\s+INTO\s+asset_transactions\b", query, re.I)
        ) and "RETURNING" not in upper
        if wants_transaction_id:
            query = query.rstrip().rstrip(";") + " RETURNING transaction_id"

        self._cursor.execute(_postgres_query(query), tuple(params or ()))
        if wants_transaction_id:
            row = self._cursor.fetchone()
            self.lastrowid = row[0] if row else None
            self._no_result = True
        return self

    def fetchone(self):
        if self._no_result:
            return None
        row = self._cursor.fetchone()
        return self._wrap(row)

    def fetchall(self):
        if self._no_result:
            return []
        return [self._wrap(row) for row in self._cursor.fetchall()]

    def _wrap(self, row):
        if row is None:
            return None
        columns = [column.name for column in self._cursor.description]
        return CompatRow(row, columns)

    def close(self):
        self._cursor.close()


class PostgresConnection:
    def __init__(self, url: str):
        self._connection = psycopg.connect(url)
        self.row_factory = None

    def cursor(self):
        return PostgresCursor(self._connection.cursor())

    def execute(self, query: str, params: Sequence[Any] | None = None):
        return self.cursor().execute(query, params)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        self.close()
        return False


def connect(database=None, timeout=15, **kwargs):
    url = database_url()
    if url:
        return PostgresConnection(url)
    return _sqlite3.connect(database, timeout=timeout, **kwargs)


def init_postgres_schema() -> None:
    url = database_url()
    if not url:
        return
    with psycopg.connect(url) as connection:
        with connection.cursor() as cursor:
            for statement in POSTGRES_SCHEMA:
                cursor.execute(statement)
